// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID        string
	OrgID     string
	OwnerKind string
	OwnerID   string
	RevokedAt sql.NullTime
}

type Approval struct {
	GrantID   string
	ID        string
	HumanID   string
	ExpiresAt time.Time
}

type ApprovalRequest struct {
	ID         string
	OrgID      string
	AgentID    string
	ItemID     string
	GrantID    string
	Action     string
	Status     string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ResolvedAt sql.NullTime
	ResolvedBy sql.NullString
	ApprovalID sql.NullString
}

type Audit struct {
	ID         int64
	At         time.Time
	OrgID      string
	AgentID    string
	ItemID     string
	Action     string
	Decision   string
	Reason     string
	ApprovalID string
}

type AuditOutbox struct {
	ID         int64
	At         time.Time
	OrgID      string
	AgentID    string
	ItemID     string
	Action     string
	Decision   string
	Reason     string
	ApprovalID string
}

type Grant struct {
	ID        string
	OrgID     string
	AgentID   string
	ItemID    string
	Level     string
	Actions   string
	ExpiresAt sql.NullTime
}

type Human struct {
	ID    string
	OrgID string
}

type Item struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	OwnerKind string
	OwnerID   string
	Uris      string
	Secret    []byte
	HasTotp   bool
	Tags      string
	Archived  bool
	HasFile   bool
	Login     string
}

type ItemVersion struct {
	ID     int64
	ItemID string
	At     time.Time
	Secret []byte
}

type OrgBilling struct {
	OrgID            string
	Plan             string
	CustomerID       string
	BillingAccountID string
	UpdatedAt        time.Time
}

type OrgKey struct {
	OrgID      string
	Wrapped    []byte
	KeyVersion int32
	CmkID      sql.NullString
	CreatedAt  time.Time
	RotatedAt  sql.NullTime
}

type OwnerKey struct {
	OrgID     string
	OwnerKind string
	OwnerID   string
	Wrapped   []byte
}

type RecoveryWrap struct {
	OrgID     string
	OwnerKind string
	OwnerID   string
	Wrapped   []byte
	CreatedAt time.Time
	ExpiresAt sql.NullTime
	UsedAt    sql.NullTime
}

type Session struct {
	ID         string
	OrgID      string
	AgentID    string
	SecretHash []byte
	ExpiresAt  time.Time
	CreatedAt  time.Time
	RevokedAt  sql.NullTime
	RenewedAt  sql.NullTime
	Ttl        int64
	MaxTtl     int64
	MaxUses    int32
	Uses       int32
}

type UsageCounter struct {
	OrgID       string
	WindowStart time.Time
	Used        int64
	Reported    int64
}

type Workload struct {
	Issuer   string
	Subject  string
	AgentID  string
	Audience string
}
