# coding: utf-8

"""
    Veil

    Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BillingView(BaseModel):
    """
    BillingView
    """ # noqa: E501
    plan: StrictStr = Field(description="Plan as enforced by the Use gate")
    used: StrictInt = Field(description="Uses consumed in the current window")
    included: Optional[StrictInt] = Field(description="Free allowance per window; null when unlimited (metering off or paid plan)")
    window_start: datetime
    window_end: datetime
    upgrade_url: Optional[StrictStr] = Field(default=None, description="Vortex checkout/portal link for capped owners")
    __properties: ClassVar[List[str]] = ["plan", "used", "included", "window_start", "window_end", "upgrade_url"]

    @field_validator('plan')
    def plan_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['free', 'active']):
            raise ValueError("must be one of enum values ('free', 'active')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillingView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if included (nullable) is None
        # and model_fields_set contains the field
        if self.included is None and "included" in self.model_fields_set:
            _dict['included'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillingView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plan": obj.get("plan"),
            "used": obj.get("used"),
            "included": obj.get("included"),
            "window_start": obj.get("window_start"),
            "window_end": obj.get("window_end"),
            "upgrade_url": obj.get("upgrade_url")
        })
        return _obj


