/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentRequest{}

// CreateAgentRequest struct for CreateAgentRequest
type CreateAgentRequest struct {
	Name string `json:"name"`
}

type _CreateAgentRequest CreateAgentRequest

// NewCreateAgentRequest instantiates a new CreateAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentRequest(name string) *CreateAgentRequest {
	this := CreateAgentRequest{}
	this.Name = name
	return &this
}

// NewCreateAgentRequestWithDefaults instantiates a new CreateAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentRequestWithDefaults() *CreateAgentRequest {
	this := CreateAgentRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAgentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgentRequest) SetName(v string) {
	o.Name = v
}

func (o CreateAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateAgentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAgentRequest := _CreateAgentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAgentRequest)

	if err != nil {
		return err
	}

	*o = CreateAgentRequest(varCreateAgentRequest)

	return err
}

type NullableCreateAgentRequest struct {
	value *CreateAgentRequest
	isSet bool
}

func (v NullableCreateAgentRequest) Get() *CreateAgentRequest {
	return v.value
}

func (v *NullableCreateAgentRequest) Set(val *CreateAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentRequest(val *CreateAgentRequest) *NullableCreateAgentRequest {
	return &NullableCreateAgentRequest{value: val, isSet: true}
}

func (v NullableCreateAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
