/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateItemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateItemRequest{}

// CreateItemRequest struct for CreateItemRequest
type CreateItemRequest struct {
	Name string   `json:"name"`
	Uri  *string  `json:"uri,omitempty"`
	Uris []string `json:"uris,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Kind *string  `json:"kind,omitempty"`
	// Vault material. Request only. Never returned.
	Secret *string `json:"secret,omitempty"`
	// TOTP seed. Request only. Never returned.
	TotpSeed *string `json:"totp_seed,omitempty"`
	// Fill username. Metadata on the item. Also sealed in the envelope. Not a secret.
	Login    *string         `json:"login,omitempty"`
	Card     *CardFields     `json:"card,omitempty"`
	Identity *IdentityFields `json:"identity,omitempty"`
}

type _CreateItemRequest CreateItemRequest

// NewCreateItemRequest instantiates a new CreateItemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateItemRequest(name string) *CreateItemRequest {
	this := CreateItemRequest{}
	this.Name = name
	return &this
}

// NewCreateItemRequestWithDefaults instantiates a new CreateItemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateItemRequestWithDefaults() *CreateItemRequest {
	this := CreateItemRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateItemRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateItemRequest) SetName(v string) {
	o.Name = v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *CreateItemRequest) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *CreateItemRequest) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *CreateItemRequest) SetUri(v string) {
	o.Uri = &v
}

// GetUris returns the Uris field value if set, zero value otherwise.
func (o *CreateItemRequest) GetUris() []string {
	if o == nil || IsNil(o.Uris) {
		var ret []string
		return ret
	}
	return o.Uris
}

// GetUrisOk returns a tuple with the Uris field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetUrisOk() ([]string, bool) {
	if o == nil || IsNil(o.Uris) {
		return nil, false
	}
	return o.Uris, true
}

// HasUris returns a boolean if a field has been set.
func (o *CreateItemRequest) HasUris() bool {
	if o != nil && !IsNil(o.Uris) {
		return true
	}

	return false
}

// SetUris gets a reference to the given []string and assigns it to the Uris field.
func (o *CreateItemRequest) SetUris(v []string) {
	o.Uris = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateItemRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateItemRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateItemRequest) SetTags(v []string) {
	o.Tags = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CreateItemRequest) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CreateItemRequest) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CreateItemRequest) SetKind(v string) {
	o.Kind = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *CreateItemRequest) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *CreateItemRequest) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *CreateItemRequest) SetSecret(v string) {
	o.Secret = &v
}

// GetTotpSeed returns the TotpSeed field value if set, zero value otherwise.
func (o *CreateItemRequest) GetTotpSeed() string {
	if o == nil || IsNil(o.TotpSeed) {
		var ret string
		return ret
	}
	return *o.TotpSeed
}

// GetTotpSeedOk returns a tuple with the TotpSeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetTotpSeedOk() (*string, bool) {
	if o == nil || IsNil(o.TotpSeed) {
		return nil, false
	}
	return o.TotpSeed, true
}

// HasTotpSeed returns a boolean if a field has been set.
func (o *CreateItemRequest) HasTotpSeed() bool {
	if o != nil && !IsNil(o.TotpSeed) {
		return true
	}

	return false
}

// SetTotpSeed gets a reference to the given string and assigns it to the TotpSeed field.
func (o *CreateItemRequest) SetTotpSeed(v string) {
	o.TotpSeed = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *CreateItemRequest) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *CreateItemRequest) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *CreateItemRequest) SetLogin(v string) {
	o.Login = &v
}

// GetCard returns the Card field value if set, zero value otherwise.
func (o *CreateItemRequest) GetCard() CardFields {
	if o == nil || IsNil(o.Card) {
		var ret CardFields
		return ret
	}
	return *o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetCardOk() (*CardFields, bool) {
	if o == nil || IsNil(o.Card) {
		return nil, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *CreateItemRequest) HasCard() bool {
	if o != nil && !IsNil(o.Card) {
		return true
	}

	return false
}

// SetCard gets a reference to the given CardFields and assigns it to the Card field.
func (o *CreateItemRequest) SetCard(v CardFields) {
	o.Card = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *CreateItemRequest) GetIdentity() IdentityFields {
	if o == nil || IsNil(o.Identity) {
		var ret IdentityFields
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateItemRequest) GetIdentityOk() (*IdentityFields, bool) {
	if o == nil || IsNil(o.Identity) {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *CreateItemRequest) HasIdentity() bool {
	if o != nil && !IsNil(o.Identity) {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given IdentityFields and assigns it to the Identity field.
func (o *CreateItemRequest) SetIdentity(v IdentityFields) {
	o.Identity = &v
}

func (o CreateItemRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateItemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	if !IsNil(o.Uris) {
		toSerialize["uris"] = o.Uris
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.TotpSeed) {
		toSerialize["totp_seed"] = o.TotpSeed
	}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !IsNil(o.Card) {
		toSerialize["card"] = o.Card
	}
	if !IsNil(o.Identity) {
		toSerialize["identity"] = o.Identity
	}
	return toSerialize, nil
}

func (o *CreateItemRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateItemRequest := _CreateItemRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateItemRequest)

	if err != nil {
		return err
	}

	*o = CreateItemRequest(varCreateItemRequest)

	return err
}

type NullableCreateItemRequest struct {
	value *CreateItemRequest
	isSet bool
}

func (v NullableCreateItemRequest) Get() *CreateItemRequest {
	return v.value
}

func (v *NullableCreateItemRequest) Set(val *CreateItemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateItemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateItemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateItemRequest(val *CreateItemRequest) *NullableCreateItemRequest {
	return &NullableCreateItemRequest{value: val, isSet: true}
}

func (v NullableCreateItemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateItemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
