/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
)

// checks if the DeleteOrg200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteOrg200Response{}

// DeleteOrg200Response struct for DeleteOrg200Response
type DeleteOrg200Response struct {
	Items *int32 `json:"items,omitempty"`
	Grants *int32 `json:"grants,omitempty"`
	Sessions *int32 `json:"sessions,omitempty"`
	Agents *int32 `json:"agents,omitempty"`
	Humans *int32 `json:"humans,omitempty"`
	Keys *int32 `json:"keys,omitempty"`
}

// NewDeleteOrg200Response instantiates a new DeleteOrg200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteOrg200Response() *DeleteOrg200Response {
	this := DeleteOrg200Response{}
	return &this
}

// NewDeleteOrg200ResponseWithDefaults instantiates a new DeleteOrg200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteOrg200ResponseWithDefaults() *DeleteOrg200Response {
	this := DeleteOrg200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetItems() int32 {
	if o == nil || IsNil(o.Items) {
		var ret int32
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given int32 and assigns it to the Items field.
func (o *DeleteOrg200Response) SetItems(v int32) {
	o.Items = &v
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetGrants() int32 {
	if o == nil || IsNil(o.Grants) {
		var ret int32
		return ret
	}
	return *o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetGrantsOk() (*int32, bool) {
	if o == nil || IsNil(o.Grants) {
		return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasGrants() bool {
	if o != nil && !IsNil(o.Grants) {
		return true
	}

	return false
}

// SetGrants gets a reference to the given int32 and assigns it to the Grants field.
func (o *DeleteOrg200Response) SetGrants(v int32) {
	o.Grants = &v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetSessions() int32 {
	if o == nil || IsNil(o.Sessions) {
		var ret int32
		return ret
	}
	return *o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetSessionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given int32 and assigns it to the Sessions field.
func (o *DeleteOrg200Response) SetSessions(v int32) {
	o.Sessions = &v
}

// GetAgents returns the Agents field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetAgents() int32 {
	if o == nil || IsNil(o.Agents) {
		var ret int32
		return ret
	}
	return *o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetAgentsOk() (*int32, bool) {
	if o == nil || IsNil(o.Agents) {
		return nil, false
	}
	return o.Agents, true
}

// HasAgents returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasAgents() bool {
	if o != nil && !IsNil(o.Agents) {
		return true
	}

	return false
}

// SetAgents gets a reference to the given int32 and assigns it to the Agents field.
func (o *DeleteOrg200Response) SetAgents(v int32) {
	o.Agents = &v
}

// GetHumans returns the Humans field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetHumans() int32 {
	if o == nil || IsNil(o.Humans) {
		var ret int32
		return ret
	}
	return *o.Humans
}

// GetHumansOk returns a tuple with the Humans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetHumansOk() (*int32, bool) {
	if o == nil || IsNil(o.Humans) {
		return nil, false
	}
	return o.Humans, true
}

// HasHumans returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasHumans() bool {
	if o != nil && !IsNil(o.Humans) {
		return true
	}

	return false
}

// SetHumans gets a reference to the given int32 and assigns it to the Humans field.
func (o *DeleteOrg200Response) SetHumans(v int32) {
	o.Humans = &v
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *DeleteOrg200Response) GetKeys() int32 {
	if o == nil || IsNil(o.Keys) {
		var ret int32
		return ret
	}
	return *o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteOrg200Response) GetKeysOk() (*int32, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *DeleteOrg200Response) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given int32 and assigns it to the Keys field.
func (o *DeleteOrg200Response) SetKeys(v int32) {
	o.Keys = &v
}

func (o DeleteOrg200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteOrg200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Grants) {
		toSerialize["grants"] = o.Grants
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	if !IsNil(o.Agents) {
		toSerialize["agents"] = o.Agents
	}
	if !IsNil(o.Humans) {
		toSerialize["humans"] = o.Humans
	}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	return toSerialize, nil
}

type NullableDeleteOrg200Response struct {
	value *DeleteOrg200Response
	isSet bool
}

func (v NullableDeleteOrg200Response) Get() *DeleteOrg200Response {
	return v.value
}

func (v *NullableDeleteOrg200Response) Set(val *DeleteOrg200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteOrg200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteOrg200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteOrg200Response(val *DeleteOrg200Response) *NullableDeleteOrg200Response {
	return &NullableDeleteOrg200Response{value: val, isSet: true}
}

func (v NullableDeleteOrg200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteOrg200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


