/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProvisionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionResponse{}

// ProvisionResponse struct for ProvisionResponse
type ProvisionResponse struct {
	Subject string `json:"subject"`
	OrgId string `json:"org_id"`
}

type _ProvisionResponse ProvisionResponse

// NewProvisionResponse instantiates a new ProvisionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionResponse(subject string, orgId string) *ProvisionResponse {
	this := ProvisionResponse{}
	this.Subject = subject
	this.OrgId = orgId
	return &this
}

// NewProvisionResponseWithDefaults instantiates a new ProvisionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionResponseWithDefaults() *ProvisionResponse {
	this := ProvisionResponse{}
	return &this
}

// GetSubject returns the Subject field value
func (o *ProvisionResponse) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *ProvisionResponse) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *ProvisionResponse) SetSubject(v string) {
	o.Subject = v
}

// GetOrgId returns the OrgId field value
func (o *ProvisionResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProvisionResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProvisionResponse) SetOrgId(v string) {
	o.OrgId = v
}

func (o ProvisionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject"] = o.Subject
	toSerialize["org_id"] = o.OrgId
	return toSerialize, nil
}

func (o *ProvisionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject",
		"org_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProvisionResponse := _ProvisionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProvisionResponse)

	if err != nil {
		return err
	}

	*o = ProvisionResponse(varProvisionResponse)

	return err
}

type NullableProvisionResponse struct {
	value *ProvisionResponse
	isSet bool
}

func (v NullableProvisionResponse) Get() *ProvisionResponse {
	return v.value
}

func (v *NullableProvisionResponse) Set(val *ProvisionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionResponse(val *ProvisionResponse) *NullableProvisionResponse {
	return &NullableProvisionResponse{value: val, isSet: true}
}

func (v NullableProvisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


