/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Item type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Item{}

// Item struct for Item
type Item struct {
	Id string `json:"id"`
	OrgId string `json:"org_id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	Owner Owner `json:"owner"`
	Uris []string `json:"uris"`
	Tags []string `json:"tags,omitempty"`
	Archived *bool `json:"archived,omitempty"`
	HasTotp *bool `json:"has_totp,omitempty"`
	HasFile *bool `json:"has_file,omitempty"`
	// Fill username. Metadata. Not a secret. Empty if unset.
	Login *string `json:"login,omitempty"`
}

type _Item Item

// NewItem instantiates a new Item object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItem(id string, orgId string, name string, kind string, owner Owner, uris []string) *Item {
	this := Item{}
	this.Id = id
	this.OrgId = orgId
	this.Name = name
	this.Kind = kind
	this.Owner = owner
	this.Uris = uris
	return &this
}

// NewItemWithDefaults instantiates a new Item object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemWithDefaults() *Item {
	this := Item{}
	return &this
}

// GetId returns the Id field value
func (o *Item) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Item) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Item) SetId(v string) {
	o.Id = v
}

// GetOrgId returns the OrgId field value
func (o *Item) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *Item) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *Item) SetOrgId(v string) {
	o.OrgId = v
}

// GetName returns the Name field value
func (o *Item) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Item) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Item) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *Item) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *Item) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *Item) SetKind(v string) {
	o.Kind = v
}

// GetOwner returns the Owner field value
func (o *Item) GetOwner() Owner {
	if o == nil {
		var ret Owner
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *Item) GetOwnerOk() (*Owner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *Item) SetOwner(v Owner) {
	o.Owner = v
}

// GetUris returns the Uris field value
func (o *Item) GetUris() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Uris
}

// GetUrisOk returns a tuple with the Uris field value
// and a boolean to check if the value has been set.
func (o *Item) GetUrisOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uris, true
}

// SetUris sets field value
func (o *Item) SetUris(v []string) {
	o.Uris = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Item) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Item) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Item) SetTags(v []string) {
	o.Tags = v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *Item) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *Item) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *Item) SetArchived(v bool) {
	o.Archived = &v
}

// GetHasTotp returns the HasTotp field value if set, zero value otherwise.
func (o *Item) GetHasTotp() bool {
	if o == nil || IsNil(o.HasTotp) {
		var ret bool
		return ret
	}
	return *o.HasTotp
}

// GetHasTotpOk returns a tuple with the HasTotp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetHasTotpOk() (*bool, bool) {
	if o == nil || IsNil(o.HasTotp) {
		return nil, false
	}
	return o.HasTotp, true
}

// HasHasTotp returns a boolean if a field has been set.
func (o *Item) HasHasTotp() bool {
	if o != nil && !IsNil(o.HasTotp) {
		return true
	}

	return false
}

// SetHasTotp gets a reference to the given bool and assigns it to the HasTotp field.
func (o *Item) SetHasTotp(v bool) {
	o.HasTotp = &v
}

// GetHasFile returns the HasFile field value if set, zero value otherwise.
func (o *Item) GetHasFile() bool {
	if o == nil || IsNil(o.HasFile) {
		var ret bool
		return ret
	}
	return *o.HasFile
}

// GetHasFileOk returns a tuple with the HasFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetHasFileOk() (*bool, bool) {
	if o == nil || IsNil(o.HasFile) {
		return nil, false
	}
	return o.HasFile, true
}

// HasHasFile returns a boolean if a field has been set.
func (o *Item) HasHasFile() bool {
	if o != nil && !IsNil(o.HasFile) {
		return true
	}

	return false
}

// SetHasFile gets a reference to the given bool and assigns it to the HasFile field.
func (o *Item) SetHasFile(v bool) {
	o.HasFile = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *Item) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Item) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *Item) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *Item) SetLogin(v string) {
	o.Login = &v
}

func (o Item) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Item) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["org_id"] = o.OrgId
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	toSerialize["owner"] = o.Owner
	toSerialize["uris"] = o.Uris
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.HasTotp) {
		toSerialize["has_totp"] = o.HasTotp
	}
	if !IsNil(o.HasFile) {
		toSerialize["has_file"] = o.HasFile
	}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	return toSerialize, nil
}

func (o *Item) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"org_id",
		"name",
		"kind",
		"owner",
		"uris",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItem := _Item{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varItem)

	if err != nil {
		return err
	}

	*o = Item(varItem)

	return err
}

type NullableItem struct {
	value *Item
	isSet bool
}

func (v NullableItem) Get() *Item {
	return v.value
}

func (v *NullableItem) Set(val *Item) {
	v.value = val
	v.isSet = true
}

func (v NullableItem) IsSet() bool {
	return v.isSet
}

func (v *NullableItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItem(val *Item) *NullableItem {
	return &NullableItem{value: val, isSet: true}
}

func (v NullableItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


