/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteResponse{}

// InviteResponse struct for InviteResponse
type InviteResponse struct {
	IdentityId string `json:"identity_id"`
	Emailed bool `json:"emailed"`
	// Only present when mail delivery is not configured (local dev).
	RecoveryUrl *string `json:"recovery_url,omitempty"`
}

type _InviteResponse InviteResponse

// NewInviteResponse instantiates a new InviteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteResponse(identityId string, emailed bool) *InviteResponse {
	this := InviteResponse{}
	this.IdentityId = identityId
	this.Emailed = emailed
	return &this
}

// NewInviteResponseWithDefaults instantiates a new InviteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteResponseWithDefaults() *InviteResponse {
	this := InviteResponse{}
	return &this
}

// GetIdentityId returns the IdentityId field value
func (o *InviteResponse) GetIdentityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value
// and a boolean to check if the value has been set.
func (o *InviteResponse) GetIdentityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityId, true
}

// SetIdentityId sets field value
func (o *InviteResponse) SetIdentityId(v string) {
	o.IdentityId = v
}

// GetEmailed returns the Emailed field value
func (o *InviteResponse) GetEmailed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Emailed
}

// GetEmailedOk returns a tuple with the Emailed field value
// and a boolean to check if the value has been set.
func (o *InviteResponse) GetEmailedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Emailed, true
}

// SetEmailed sets field value
func (o *InviteResponse) SetEmailed(v bool) {
	o.Emailed = v
}

// GetRecoveryUrl returns the RecoveryUrl field value if set, zero value otherwise.
func (o *InviteResponse) GetRecoveryUrl() string {
	if o == nil || IsNil(o.RecoveryUrl) {
		var ret string
		return ret
	}
	return *o.RecoveryUrl
}

// GetRecoveryUrlOk returns a tuple with the RecoveryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteResponse) GetRecoveryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RecoveryUrl) {
		return nil, false
	}
	return o.RecoveryUrl, true
}

// HasRecoveryUrl returns a boolean if a field has been set.
func (o *InviteResponse) HasRecoveryUrl() bool {
	if o != nil && !IsNil(o.RecoveryUrl) {
		return true
	}

	return false
}

// SetRecoveryUrl gets a reference to the given string and assigns it to the RecoveryUrl field.
func (o *InviteResponse) SetRecoveryUrl(v string) {
	o.RecoveryUrl = &v
}

func (o InviteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identity_id"] = o.IdentityId
	toSerialize["emailed"] = o.Emailed
	if !IsNil(o.RecoveryUrl) {
		toSerialize["recovery_url"] = o.RecoveryUrl
	}
	return toSerialize, nil
}

func (o *InviteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identity_id",
		"emailed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteResponse := _InviteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteResponse)

	if err != nil {
		return err
	}

	*o = InviteResponse(varInviteResponse)

	return err
}

type NullableInviteResponse struct {
	value *InviteResponse
	isSet bool
}

func (v NullableInviteResponse) Get() *InviteResponse {
	return v.value
}

func (v *NullableInviteResponse) Set(val *InviteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteResponse(val *InviteResponse) *NullableInviteResponse {
	return &NullableInviteResponse{value: val, isSet: true}
}

func (v NullableInviteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


