/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSessionResponse{}

// CreateSessionResponse Token is create-only. Never list. Never MCP.
type CreateSessionResponse struct {
	Id string `json:"id"`
	OrgId string `json:"org_id"`
	AgentId string `json:"agent_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	RenewedAt *time.Time `json:"renewed_at,omitempty"`
	Ttl int32 `json:"ttl"`
	MaxTtl int32 `json:"max_ttl"`
	MaxUses int32 `json:"max_uses"`
	// Use calls that passed authorization and reached upstream consumption.
	Uses int32 `json:"uses"`
	Token string `json:"token"`
}

type _CreateSessionResponse CreateSessionResponse

// NewCreateSessionResponse instantiates a new CreateSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSessionResponse(id string, orgId string, agentId string, expiresAt time.Time, createdAt time.Time, ttl int32, maxTtl int32, maxUses int32, uses int32, token string) *CreateSessionResponse {
	this := CreateSessionResponse{}
	this.Id = id
	this.OrgId = orgId
	this.AgentId = agentId
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	this.Ttl = ttl
	this.MaxTtl = maxTtl
	this.MaxUses = maxUses
	this.Uses = uses
	this.Token = token
	return &this
}

// NewCreateSessionResponseWithDefaults instantiates a new CreateSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSessionResponseWithDefaults() *CreateSessionResponse {
	this := CreateSessionResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateSessionResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateSessionResponse) SetId(v string) {
	o.Id = v
}

// GetOrgId returns the OrgId field value
func (o *CreateSessionResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *CreateSessionResponse) SetOrgId(v string) {
	o.OrgId = v
}

// GetAgentId returns the AgentId field value
func (o *CreateSessionResponse) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *CreateSessionResponse) SetAgentId(v string) {
	o.AgentId = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CreateSessionResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CreateSessionResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateSessionResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateSessionResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *CreateSessionResponse) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *CreateSessionResponse) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given time.Time and assigns it to the RevokedAt field.
func (o *CreateSessionResponse) SetRevokedAt(v time.Time) {
	o.RevokedAt = &v
}

// GetRenewedAt returns the RenewedAt field value if set, zero value otherwise.
func (o *CreateSessionResponse) GetRenewedAt() time.Time {
	if o == nil || IsNil(o.RenewedAt) {
		var ret time.Time
		return ret
	}
	return *o.RenewedAt
}

// GetRenewedAtOk returns a tuple with the RenewedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetRenewedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RenewedAt) {
		return nil, false
	}
	return o.RenewedAt, true
}

// HasRenewedAt returns a boolean if a field has been set.
func (o *CreateSessionResponse) HasRenewedAt() bool {
	if o != nil && !IsNil(o.RenewedAt) {
		return true
	}

	return false
}

// SetRenewedAt gets a reference to the given time.Time and assigns it to the RenewedAt field.
func (o *CreateSessionResponse) SetRenewedAt(v time.Time) {
	o.RenewedAt = &v
}

// GetTtl returns the Ttl field value
func (o *CreateSessionResponse) GetTtl() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetTtlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ttl, true
}

// SetTtl sets field value
func (o *CreateSessionResponse) SetTtl(v int32) {
	o.Ttl = v
}

// GetMaxTtl returns the MaxTtl field value
func (o *CreateSessionResponse) GetMaxTtl() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxTtl
}

// GetMaxTtlOk returns a tuple with the MaxTtl field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetMaxTtlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTtl, true
}

// SetMaxTtl sets field value
func (o *CreateSessionResponse) SetMaxTtl(v int32) {
	o.MaxTtl = v
}

// GetMaxUses returns the MaxUses field value
func (o *CreateSessionResponse) GetMaxUses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxUses
}

// GetMaxUsesOk returns a tuple with the MaxUses field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetMaxUsesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxUses, true
}

// SetMaxUses sets field value
func (o *CreateSessionResponse) SetMaxUses(v int32) {
	o.MaxUses = v
}

// GetUses returns the Uses field value
func (o *CreateSessionResponse) GetUses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Uses
}

// GetUsesOk returns a tuple with the Uses field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetUsesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uses, true
}

// SetUses sets field value
func (o *CreateSessionResponse) SetUses(v int32) {
	o.Uses = v
}

// GetToken returns the Token field value
func (o *CreateSessionResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CreateSessionResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CreateSessionResponse) SetToken(v string) {
	o.Token = v
}

func (o CreateSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["org_id"] = o.OrgId
	toSerialize["agent_id"] = o.AgentId
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	if !IsNil(o.RenewedAt) {
		toSerialize["renewed_at"] = o.RenewedAt
	}
	toSerialize["ttl"] = o.Ttl
	toSerialize["max_ttl"] = o.MaxTtl
	toSerialize["max_uses"] = o.MaxUses
	toSerialize["uses"] = o.Uses
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *CreateSessionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"org_id",
		"agent_id",
		"expires_at",
		"created_at",
		"ttl",
		"max_ttl",
		"max_uses",
		"uses",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSessionResponse := _CreateSessionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSessionResponse)

	if err != nil {
		return err
	}

	*o = CreateSessionResponse(varCreateSessionResponse)

	return err
}

type NullableCreateSessionResponse struct {
	value *CreateSessionResponse
	isSet bool
}

func (v NullableCreateSessionResponse) Get() *CreateSessionResponse {
	return v.value
}

func (v *NullableCreateSessionResponse) Set(val *CreateSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSessionResponse(val *CreateSessionResponse) *NullableCreateSessionResponse {
	return &NullableCreateSessionResponse{value: val, isSet: true}
}

func (v NullableCreateSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


