/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BillingView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingView{}

// BillingView struct for BillingView
type BillingView struct {
	// Plan as enforced by the Use gate
	Plan string `json:"plan"`
	// Uses consumed in the current window
	Used int64 `json:"used"`
	// Free allowance per window; null when unlimited (metering off or paid plan)
	Included NullableInt64 `json:"included"`
	WindowStart time.Time `json:"window_start"`
	WindowEnd time.Time `json:"window_end"`
	// Vortex checkout/portal link for capped owners
	UpgradeUrl *string `json:"upgrade_url,omitempty"`
}

type _BillingView BillingView

// NewBillingView instantiates a new BillingView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingView(plan string, used int64, included NullableInt64, windowStart time.Time, windowEnd time.Time) *BillingView {
	this := BillingView{}
	this.Plan = plan
	this.Used = used
	this.Included = included
	this.WindowStart = windowStart
	this.WindowEnd = windowEnd
	return &this
}

// NewBillingViewWithDefaults instantiates a new BillingView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingViewWithDefaults() *BillingView {
	this := BillingView{}
	return &this
}

// GetPlan returns the Plan field value
func (o *BillingView) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *BillingView) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *BillingView) SetPlan(v string) {
	o.Plan = v
}

// GetUsed returns the Used field value
func (o *BillingView) GetUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *BillingView) GetUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *BillingView) SetUsed(v int64) {
	o.Used = v
}

// GetIncluded returns the Included field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *BillingView) GetIncluded() int64 {
	if o == nil || o.Included.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Included.Get()
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingView) GetIncludedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included.Get(), o.Included.IsSet()
}

// SetIncluded sets field value
func (o *BillingView) SetIncluded(v int64) {
	o.Included.Set(&v)
}

// GetWindowStart returns the WindowStart field value
func (o *BillingView) GetWindowStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.WindowStart
}

// GetWindowStartOk returns a tuple with the WindowStart field value
// and a boolean to check if the value has been set.
func (o *BillingView) GetWindowStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowStart, true
}

// SetWindowStart sets field value
func (o *BillingView) SetWindowStart(v time.Time) {
	o.WindowStart = v
}

// GetWindowEnd returns the WindowEnd field value
func (o *BillingView) GetWindowEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.WindowEnd
}

// GetWindowEndOk returns a tuple with the WindowEnd field value
// and a boolean to check if the value has been set.
func (o *BillingView) GetWindowEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindowEnd, true
}

// SetWindowEnd sets field value
func (o *BillingView) SetWindowEnd(v time.Time) {
	o.WindowEnd = v
}

// GetUpgradeUrl returns the UpgradeUrl field value if set, zero value otherwise.
func (o *BillingView) GetUpgradeUrl() string {
	if o == nil || IsNil(o.UpgradeUrl) {
		var ret string
		return ret
	}
	return *o.UpgradeUrl
}

// GetUpgradeUrlOk returns a tuple with the UpgradeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingView) GetUpgradeUrlOk() (*string, bool) {
	if o == nil || IsNil(o.UpgradeUrl) {
		return nil, false
	}
	return o.UpgradeUrl, true
}

// HasUpgradeUrl returns a boolean if a field has been set.
func (o *BillingView) HasUpgradeUrl() bool {
	if o != nil && !IsNil(o.UpgradeUrl) {
		return true
	}

	return false
}

// SetUpgradeUrl gets a reference to the given string and assigns it to the UpgradeUrl field.
func (o *BillingView) SetUpgradeUrl(v string) {
	o.UpgradeUrl = &v
}

func (o BillingView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan"] = o.Plan
	toSerialize["used"] = o.Used
	toSerialize["included"] = o.Included.Get()
	toSerialize["window_start"] = o.WindowStart
	toSerialize["window_end"] = o.WindowEnd
	if !IsNil(o.UpgradeUrl) {
		toSerialize["upgrade_url"] = o.UpgradeUrl
	}
	return toSerialize, nil
}

func (o *BillingView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
		"used",
		"included",
		"window_start",
		"window_end",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingView := _BillingView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingView)

	if err != nil {
		return err
	}

	*o = BillingView(varBillingView)

	return err
}

type NullableBillingView struct {
	value *BillingView
	isSet bool
}

func (v NullableBillingView) Get() *BillingView {
	return v.value
}

func (v *NullableBillingView) Set(val *BillingView) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingView) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingView(val *BillingView) *NullableBillingView {
	return &NullableBillingView{value: val, isSet: true}
}

func (v NullableBillingView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


