/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddGroupMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddGroupMemberRequest{}

// AddGroupMemberRequest struct for AddGroupMemberRequest
type AddGroupMemberRequest struct {
	MemberKind string `json:"member_kind"`
	// Agent id, or Kratos identity id for humans.
	MemberId string `json:"member_id"`
}

type _AddGroupMemberRequest AddGroupMemberRequest

// NewAddGroupMemberRequest instantiates a new AddGroupMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddGroupMemberRequest(memberKind string, memberId string) *AddGroupMemberRequest {
	this := AddGroupMemberRequest{}
	this.MemberKind = memberKind
	this.MemberId = memberId
	return &this
}

// NewAddGroupMemberRequestWithDefaults instantiates a new AddGroupMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddGroupMemberRequestWithDefaults() *AddGroupMemberRequest {
	this := AddGroupMemberRequest{}
	return &this
}

// GetMemberKind returns the MemberKind field value
func (o *AddGroupMemberRequest) GetMemberKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemberKind
}

// GetMemberKindOk returns a tuple with the MemberKind field value
// and a boolean to check if the value has been set.
func (o *AddGroupMemberRequest) GetMemberKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberKind, true
}

// SetMemberKind sets field value
func (o *AddGroupMemberRequest) SetMemberKind(v string) {
	o.MemberKind = v
}

// GetMemberId returns the MemberId field value
func (o *AddGroupMemberRequest) GetMemberId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemberId
}

// GetMemberIdOk returns a tuple with the MemberId field value
// and a boolean to check if the value has been set.
func (o *AddGroupMemberRequest) GetMemberIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberId, true
}

// SetMemberId sets field value
func (o *AddGroupMemberRequest) SetMemberId(v string) {
	o.MemberId = v
}

func (o AddGroupMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddGroupMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["member_kind"] = o.MemberKind
	toSerialize["member_id"] = o.MemberId
	return toSerialize, nil
}

func (o *AddGroupMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"member_kind",
		"member_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddGroupMemberRequest := _AddGroupMemberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddGroupMemberRequest)

	if err != nil {
		return err
	}

	*o = AddGroupMemberRequest(varAddGroupMemberRequest)

	return err
}

type NullableAddGroupMemberRequest struct {
	value *AddGroupMemberRequest
	isSet bool
}

func (v NullableAddGroupMemberRequest) Get() *AddGroupMemberRequest {
	return v.value
}

func (v *NullableAddGroupMemberRequest) Set(val *AddGroupMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddGroupMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddGroupMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddGroupMemberRequest(val *AddGroupMemberRequest) *NullableAddGroupMemberRequest {
	return &NullableAddGroupMemberRequest{value: val, isSet: true}
}

func (v NullableAddGroupMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddGroupMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


