/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsResponse{}

// EventsResponse struct for EventsResponse
type EventsResponse struct {
	Events []AuditEvent `json:"events"`
}

type _EventsResponse EventsResponse

// NewEventsResponse instantiates a new EventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsResponse(events []AuditEvent) *EventsResponse {
	this := EventsResponse{}
	this.Events = events
	return &this
}

// NewEventsResponseWithDefaults instantiates a new EventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsResponseWithDefaults() *EventsResponse {
	this := EventsResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *EventsResponse) GetEvents() []AuditEvent {
	if o == nil {
		var ret []AuditEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EventsResponse) GetEventsOk() ([]AuditEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EventsResponse) SetEvents(v []AuditEvent) {
	o.Events = v
}

func (o EventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *EventsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventsResponse := _EventsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventsResponse)

	if err != nil {
		return err
	}

	*o = EventsResponse(varEventsResponse)

	return err
}

type NullableEventsResponse struct {
	value *EventsResponse
	isSet bool
}

func (v NullableEventsResponse) Get() *EventsResponse {
	return v.value
}

func (v *NullableEventsResponse) Set(val *EventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsResponse(val *EventsResponse) *NullableEventsResponse {
	return &NullableEventsResponse{value: val, isSet: true}
}

func (v NullableEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
