/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
)

// checks if the CardFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardFields{}

// CardFields Request only. Never returned. Never MCP.
type CardFields struct {
	Number *string `json:"number,omitempty"`
	ExpMonth *string `json:"exp_month,omitempty"`
	ExpYear *string `json:"exp_year,omitempty"`
	Cvv *string `json:"cvv,omitempty"`
	Holder *string `json:"holder,omitempty"`
}

// NewCardFields instantiates a new CardFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardFields() *CardFields {
	this := CardFields{}
	return &this
}

// NewCardFieldsWithDefaults instantiates a new CardFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardFieldsWithDefaults() *CardFields {
	this := CardFields{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *CardFields) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardFields) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *CardFields) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *CardFields) SetNumber(v string) {
	o.Number = &v
}

// GetExpMonth returns the ExpMonth field value if set, zero value otherwise.
func (o *CardFields) GetExpMonth() string {
	if o == nil || IsNil(o.ExpMonth) {
		var ret string
		return ret
	}
	return *o.ExpMonth
}

// GetExpMonthOk returns a tuple with the ExpMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardFields) GetExpMonthOk() (*string, bool) {
	if o == nil || IsNil(o.ExpMonth) {
		return nil, false
	}
	return o.ExpMonth, true
}

// HasExpMonth returns a boolean if a field has been set.
func (o *CardFields) HasExpMonth() bool {
	if o != nil && !IsNil(o.ExpMonth) {
		return true
	}

	return false
}

// SetExpMonth gets a reference to the given string and assigns it to the ExpMonth field.
func (o *CardFields) SetExpMonth(v string) {
	o.ExpMonth = &v
}

// GetExpYear returns the ExpYear field value if set, zero value otherwise.
func (o *CardFields) GetExpYear() string {
	if o == nil || IsNil(o.ExpYear) {
		var ret string
		return ret
	}
	return *o.ExpYear
}

// GetExpYearOk returns a tuple with the ExpYear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardFields) GetExpYearOk() (*string, bool) {
	if o == nil || IsNil(o.ExpYear) {
		return nil, false
	}
	return o.ExpYear, true
}

// HasExpYear returns a boolean if a field has been set.
func (o *CardFields) HasExpYear() bool {
	if o != nil && !IsNil(o.ExpYear) {
		return true
	}

	return false
}

// SetExpYear gets a reference to the given string and assigns it to the ExpYear field.
func (o *CardFields) SetExpYear(v string) {
	o.ExpYear = &v
}

// GetCvv returns the Cvv field value if set, zero value otherwise.
func (o *CardFields) GetCvv() string {
	if o == nil || IsNil(o.Cvv) {
		var ret string
		return ret
	}
	return *o.Cvv
}

// GetCvvOk returns a tuple with the Cvv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardFields) GetCvvOk() (*string, bool) {
	if o == nil || IsNil(o.Cvv) {
		return nil, false
	}
	return o.Cvv, true
}

// HasCvv returns a boolean if a field has been set.
func (o *CardFields) HasCvv() bool {
	if o != nil && !IsNil(o.Cvv) {
		return true
	}

	return false
}

// SetCvv gets a reference to the given string and assigns it to the Cvv field.
func (o *CardFields) SetCvv(v string) {
	o.Cvv = &v
}

// GetHolder returns the Holder field value if set, zero value otherwise.
func (o *CardFields) GetHolder() string {
	if o == nil || IsNil(o.Holder) {
		var ret string
		return ret
	}
	return *o.Holder
}

// GetHolderOk returns a tuple with the Holder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardFields) GetHolderOk() (*string, bool) {
	if o == nil || IsNil(o.Holder) {
		return nil, false
	}
	return o.Holder, true
}

// HasHolder returns a boolean if a field has been set.
func (o *CardFields) HasHolder() bool {
	if o != nil && !IsNil(o.Holder) {
		return true
	}

	return false
}

// SetHolder gets a reference to the given string and assigns it to the Holder field.
func (o *CardFields) SetHolder(v string) {
	o.Holder = &v
}

func (o CardFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.ExpMonth) {
		toSerialize["exp_month"] = o.ExpMonth
	}
	if !IsNil(o.ExpYear) {
		toSerialize["exp_year"] = o.ExpYear
	}
	if !IsNil(o.Cvv) {
		toSerialize["cvv"] = o.Cvv
	}
	if !IsNil(o.Holder) {
		toSerialize["holder"] = o.Holder
	}
	return toSerialize, nil
}

type NullableCardFields struct {
	value *CardFields
	isSet bool
}

func (v NullableCardFields) Get() *CardFields {
	return v.value
}

func (v *NullableCardFields) Set(val *CardFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCardFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCardFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardFields(val *CardFields) *NullableCardFields {
	return &NullableCardFields{value: val, isSet: true}
}

func (v NullableCardFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


