/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuditFeedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditFeedResponse{}

// AuditFeedResponse struct for AuditFeedResponse
type AuditFeedResponse struct {
	Events []AuditFeedEvent `json:"events"`
	// Cursor for the next page — pass as ?after=. Equals the last event id, or the requested cursor when the page is empty.
	NextAfter int64 `json:"next_after"`
}

type _AuditFeedResponse AuditFeedResponse

// NewAuditFeedResponse instantiates a new AuditFeedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditFeedResponse(events []AuditFeedEvent, nextAfter int64) *AuditFeedResponse {
	this := AuditFeedResponse{}
	this.Events = events
	this.NextAfter = nextAfter
	return &this
}

// NewAuditFeedResponseWithDefaults instantiates a new AuditFeedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditFeedResponseWithDefaults() *AuditFeedResponse {
	this := AuditFeedResponse{}
	return &this
}

// GetEvents returns the Events field value
func (o *AuditFeedResponse) GetEvents() []AuditFeedEvent {
	if o == nil {
		var ret []AuditFeedEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *AuditFeedResponse) GetEventsOk() ([]AuditFeedEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *AuditFeedResponse) SetEvents(v []AuditFeedEvent) {
	o.Events = v
}

// GetNextAfter returns the NextAfter field value
func (o *AuditFeedResponse) GetNextAfter() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NextAfter
}

// GetNextAfterOk returns a tuple with the NextAfter field value
// and a boolean to check if the value has been set.
func (o *AuditFeedResponse) GetNextAfterOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextAfter, true
}

// SetNextAfter sets field value
func (o *AuditFeedResponse) SetNextAfter(v int64) {
	o.NextAfter = v
}

func (o AuditFeedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditFeedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	toSerialize["next_after"] = o.NextAfter
	return toSerialize, nil
}

func (o *AuditFeedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
		"next_after",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditFeedResponse := _AuditFeedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditFeedResponse)

	if err != nil {
		return err
	}

	*o = AuditFeedResponse(varAuditFeedResponse)

	return err
}

type NullableAuditFeedResponse struct {
	value *AuditFeedResponse
	isSet bool
}

func (v NullableAuditFeedResponse) Get() *AuditFeedResponse {
	return v.value
}

func (v *NullableAuditFeedResponse) Set(val *AuditFeedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditFeedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditFeedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditFeedResponse(val *AuditFeedResponse) *NullableAuditFeedResponse {
	return &NullableAuditFeedResponse{value: val, isSet: true}
}

func (v NullableAuditFeedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditFeedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


