/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingCheckout type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingCheckout{}

// BillingCheckout struct for BillingCheckout
type BillingCheckout struct {
	// Fresh hosted Vortex checkout URL for this org — navigate immediately, single-use
	CheckoutUrl string `json:"checkout_url"`
}

type _BillingCheckout BillingCheckout

// NewBillingCheckout instantiates a new BillingCheckout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingCheckout(checkoutUrl string) *BillingCheckout {
	this := BillingCheckout{}
	this.CheckoutUrl = checkoutUrl
	return &this
}

// NewBillingCheckoutWithDefaults instantiates a new BillingCheckout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingCheckoutWithDefaults() *BillingCheckout {
	this := BillingCheckout{}
	return &this
}

// GetCheckoutUrl returns the CheckoutUrl field value
func (o *BillingCheckout) GetCheckoutUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CheckoutUrl
}

// GetCheckoutUrlOk returns a tuple with the CheckoutUrl field value
// and a boolean to check if the value has been set.
func (o *BillingCheckout) GetCheckoutUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CheckoutUrl, true
}

// SetCheckoutUrl sets field value
func (o *BillingCheckout) SetCheckoutUrl(v string) {
	o.CheckoutUrl = v
}

func (o BillingCheckout) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingCheckout) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["checkout_url"] = o.CheckoutUrl
	return toSerialize, nil
}

func (o *BillingCheckout) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"checkout_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingCheckout := _BillingCheckout{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingCheckout)

	if err != nil {
		return err
	}

	*o = BillingCheckout(varBillingCheckout)

	return err
}

type NullableBillingCheckout struct {
	value *BillingCheckout
	isSet bool
}

func (v NullableBillingCheckout) Get() *BillingCheckout {
	return v.value
}

func (v *NullableBillingCheckout) Set(val *BillingCheckout) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingCheckout) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingCheckout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingCheckout(val *BillingCheckout) *NullableBillingCheckout {
	return &NullableBillingCheckout{value: val, isSet: true}
}

func (v NullableBillingCheckout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingCheckout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


