/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsResponse{}

// GroupsResponse struct for GroupsResponse
type GroupsResponse struct {
	Groups []Group `json:"groups"`
}

type _GroupsResponse GroupsResponse

// NewGroupsResponse instantiates a new GroupsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsResponse(groups []Group) *GroupsResponse {
	this := GroupsResponse{}
	this.Groups = groups
	return &this
}

// NewGroupsResponseWithDefaults instantiates a new GroupsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsResponseWithDefaults() *GroupsResponse {
	this := GroupsResponse{}
	return &this
}

// GetGroups returns the Groups field value
func (o *GroupsResponse) GetGroups() []Group {
	if o == nil {
		var ret []Group
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *GroupsResponse) GetGroupsOk() ([]Group, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *GroupsResponse) SetGroups(v []Group) {
	o.Groups = v
}

func (o GroupsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groups"] = o.Groups
	return toSerialize, nil
}

func (o *GroupsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupsResponse := _GroupsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupsResponse)

	if err != nil {
		return err
	}

	*o = GroupsResponse(varGroupsResponse)

	return err
}

type NullableGroupsResponse struct {
	value *GroupsResponse
	isSet bool
}

func (v NullableGroupsResponse) Get() *GroupsResponse {
	return v.value
}

func (v *NullableGroupsResponse) Set(val *GroupsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsResponse(val *GroupsResponse) *NullableGroupsResponse {
	return &NullableGroupsResponse{value: val, isSet: true}
}

func (v NullableGroupsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


