/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VaultReportFinding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VaultReportFinding{}

// VaultReportFinding struct for VaultReportFinding
type VaultReportFinding struct {
	ItemId string `json:"item_id"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	Uri *string `json:"uri,omitempty"`
	Weak []string `json:"weak,omitempty"`
	Reused *int32 `json:"reused,omitempty"`
	Pwned int32 `json:"pwned"`
}

type _VaultReportFinding VaultReportFinding

// NewVaultReportFinding instantiates a new VaultReportFinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVaultReportFinding(itemId string, name string, kind string, pwned int32) *VaultReportFinding {
	this := VaultReportFinding{}
	this.ItemId = itemId
	this.Name = name
	this.Kind = kind
	this.Pwned = pwned
	return &this
}

// NewVaultReportFindingWithDefaults instantiates a new VaultReportFinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultReportFindingWithDefaults() *VaultReportFinding {
	this := VaultReportFinding{}
	return &this
}

// GetItemId returns the ItemId field value
func (o *VaultReportFinding) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *VaultReportFinding) SetItemId(v string) {
	o.ItemId = v
}

// GetName returns the Name field value
func (o *VaultReportFinding) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VaultReportFinding) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *VaultReportFinding) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *VaultReportFinding) SetKind(v string) {
	o.Kind = v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *VaultReportFinding) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *VaultReportFinding) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *VaultReportFinding) SetUri(v string) {
	o.Uri = &v
}

// GetWeak returns the Weak field value if set, zero value otherwise.
func (o *VaultReportFinding) GetWeak() []string {
	if o == nil || IsNil(o.Weak) {
		var ret []string
		return ret
	}
	return o.Weak
}

// GetWeakOk returns a tuple with the Weak field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetWeakOk() ([]string, bool) {
	if o == nil || IsNil(o.Weak) {
		return nil, false
	}
	return o.Weak, true
}

// HasWeak returns a boolean if a field has been set.
func (o *VaultReportFinding) HasWeak() bool {
	if o != nil && !IsNil(o.Weak) {
		return true
	}

	return false
}

// SetWeak gets a reference to the given []string and assigns it to the Weak field.
func (o *VaultReportFinding) SetWeak(v []string) {
	o.Weak = v
}

// GetReused returns the Reused field value if set, zero value otherwise.
func (o *VaultReportFinding) GetReused() int32 {
	if o == nil || IsNil(o.Reused) {
		var ret int32
		return ret
	}
	return *o.Reused
}

// GetReusedOk returns a tuple with the Reused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetReusedOk() (*int32, bool) {
	if o == nil || IsNil(o.Reused) {
		return nil, false
	}
	return o.Reused, true
}

// HasReused returns a boolean if a field has been set.
func (o *VaultReportFinding) HasReused() bool {
	if o != nil && !IsNil(o.Reused) {
		return true
	}

	return false
}

// SetReused gets a reference to the given int32 and assigns it to the Reused field.
func (o *VaultReportFinding) SetReused(v int32) {
	o.Reused = &v
}

// GetPwned returns the Pwned field value
func (o *VaultReportFinding) GetPwned() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pwned
}

// GetPwnedOk returns a tuple with the Pwned field value
// and a boolean to check if the value has been set.
func (o *VaultReportFinding) GetPwnedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pwned, true
}

// SetPwned sets field value
func (o *VaultReportFinding) SetPwned(v int32) {
	o.Pwned = v
}

func (o VaultReportFinding) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VaultReportFinding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["item_id"] = o.ItemId
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	if !IsNil(o.Weak) {
		toSerialize["weak"] = o.Weak
	}
	if !IsNil(o.Reused) {
		toSerialize["reused"] = o.Reused
	}
	toSerialize["pwned"] = o.Pwned
	return toSerialize, nil
}

func (o *VaultReportFinding) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item_id",
		"name",
		"kind",
		"pwned",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVaultReportFinding := _VaultReportFinding{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVaultReportFinding)

	if err != nil {
		return err
	}

	*o = VaultReportFinding(varVaultReportFinding)

	return err
}

type NullableVaultReportFinding struct {
	value *VaultReportFinding
	isSet bool
}

func (v NullableVaultReportFinding) Get() *VaultReportFinding {
	return v.value
}

func (v *NullableVaultReportFinding) Set(val *VaultReportFinding) {
	v.value = val
	v.isSet = true
}

func (v NullableVaultReportFinding) IsSet() bool {
	return v.isSet
}

func (v *NullableVaultReportFinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVaultReportFinding(val *VaultReportFinding) *NullableVaultReportFinding {
	return &NullableVaultReportFinding{value: val, isSet: true}
}

func (v NullableVaultReportFinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVaultReportFinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


