/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGrantRequest{}

// CreateGrantRequest struct for CreateGrantRequest
type CreateGrantRequest struct {
	// Agent id. XOR human.
	Agent *string `json:"agent,omitempty"`
	// Kratos identity id. Same Grant.agent_id. Not email. XOR agent.
	Human *string `json:"human,omitempty"`
	Item string `json:"item"`
	Level string `json:"level"`
	// Go duration. Empty is forever.
	Expires *string `json:"expires,omitempty"`
}

type _CreateGrantRequest CreateGrantRequest

// NewCreateGrantRequest instantiates a new CreateGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGrantRequest(item string, level string) *CreateGrantRequest {
	this := CreateGrantRequest{}
	this.Item = item
	this.Level = level
	return &this
}

// NewCreateGrantRequestWithDefaults instantiates a new CreateGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGrantRequestWithDefaults() *CreateGrantRequest {
	this := CreateGrantRequest{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *CreateGrantRequest) GetAgent() string {
	if o == nil || IsNil(o.Agent) {
		var ret string
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrantRequest) GetAgentOk() (*string, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *CreateGrantRequest) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given string and assigns it to the Agent field.
func (o *CreateGrantRequest) SetAgent(v string) {
	o.Agent = &v
}

// GetHuman returns the Human field value if set, zero value otherwise.
func (o *CreateGrantRequest) GetHuman() string {
	if o == nil || IsNil(o.Human) {
		var ret string
		return ret
	}
	return *o.Human
}

// GetHumanOk returns a tuple with the Human field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrantRequest) GetHumanOk() (*string, bool) {
	if o == nil || IsNil(o.Human) {
		return nil, false
	}
	return o.Human, true
}

// HasHuman returns a boolean if a field has been set.
func (o *CreateGrantRequest) HasHuman() bool {
	if o != nil && !IsNil(o.Human) {
		return true
	}

	return false
}

// SetHuman gets a reference to the given string and assigns it to the Human field.
func (o *CreateGrantRequest) SetHuman(v string) {
	o.Human = &v
}

// GetItem returns the Item field value
func (o *CreateGrantRequest) GetItem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *CreateGrantRequest) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *CreateGrantRequest) SetItem(v string) {
	o.Item = v
}

// GetLevel returns the Level field value
func (o *CreateGrantRequest) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *CreateGrantRequest) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *CreateGrantRequest) SetLevel(v string) {
	o.Level = v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *CreateGrantRequest) GetExpires() string {
	if o == nil || IsNil(o.Expires) {
		var ret string
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGrantRequest) GetExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *CreateGrantRequest) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given string and assigns it to the Expires field.
func (o *CreateGrantRequest) SetExpires(v string) {
	o.Expires = &v
}

func (o CreateGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	if !IsNil(o.Human) {
		toSerialize["human"] = o.Human
	}
	toSerialize["item"] = o.Item
	toSerialize["level"] = o.Level
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	return toSerialize, nil
}

func (o *CreateGrantRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"item",
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateGrantRequest := _CreateGrantRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateGrantRequest)

	if err != nil {
		return err
	}

	*o = CreateGrantRequest(varCreateGrantRequest)

	return err
}

type NullableCreateGrantRequest struct {
	value *CreateGrantRequest
	isSet bool
}

func (v NullableCreateGrantRequest) Get() *CreateGrantRequest {
	return v.value
}

func (v *NullableCreateGrantRequest) Set(val *CreateGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGrantRequest(val *CreateGrantRequest) *NullableCreateGrantRequest {
	return &NullableCreateGrantRequest{value: val, isSet: true}
}

func (v NullableCreateGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


