/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMembersResponse{}

// GroupMembersResponse struct for GroupMembersResponse
type GroupMembersResponse struct {
	Members []GroupMember `json:"members"`
}

type _GroupMembersResponse GroupMembersResponse

// NewGroupMembersResponse instantiates a new GroupMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMembersResponse(members []GroupMember) *GroupMembersResponse {
	this := GroupMembersResponse{}
	this.Members = members
	return &this
}

// NewGroupMembersResponseWithDefaults instantiates a new GroupMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMembersResponseWithDefaults() *GroupMembersResponse {
	this := GroupMembersResponse{}
	return &this
}

// GetMembers returns the Members field value
func (o *GroupMembersResponse) GetMembers() []GroupMember {
	if o == nil {
		var ret []GroupMember
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *GroupMembersResponse) GetMembersOk() ([]GroupMember, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *GroupMembersResponse) SetMembers(v []GroupMember) {
	o.Members = v
}

func (o GroupMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["members"] = o.Members
	return toSerialize, nil
}

func (o *GroupMembersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMembersResponse := _GroupMembersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupMembersResponse)

	if err != nil {
		return err
	}

	*o = GroupMembersResponse(varGroupMembersResponse)

	return err
}

type NullableGroupMembersResponse struct {
	value *GroupMembersResponse
	isSet bool
}

func (v NullableGroupMembersResponse) Get() *GroupMembersResponse {
	return v.value
}

func (v *NullableGroupMembersResponse) Set(val *GroupMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMembersResponse(val *GroupMembersResponse) *NullableGroupMembersResponse {
	return &NullableGroupMembersResponse{value: val, isSet: true}
}

func (v NullableGroupMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


