/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AuditFeedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditFeedEvent{}

// AuditFeedEvent struct for AuditFeedEvent
type AuditFeedEvent struct {
	// Committed row id — monotonically increasing per append; the feed cursor.
	Id int64 `json:"id"`
	Time time.Time `json:"time"`
	OrgId string `json:"org_id"`
	AgentId string `json:"agent_id"`
	ItemId string `json:"item_id"`
	Action string `json:"action"`
	Decision string `json:"decision"`
	Reason *string `json:"reason,omitempty"`
	ApprovalId *string `json:"approval_id,omitempty"`
}

type _AuditFeedEvent AuditFeedEvent

// NewAuditFeedEvent instantiates a new AuditFeedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditFeedEvent(id int64, time time.Time, orgId string, agentId string, itemId string, action string, decision string) *AuditFeedEvent {
	this := AuditFeedEvent{}
	this.Id = id
	this.Time = time
	this.OrgId = orgId
	this.AgentId = agentId
	this.ItemId = itemId
	this.Action = action
	this.Decision = decision
	return &this
}

// NewAuditFeedEventWithDefaults instantiates a new AuditFeedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditFeedEventWithDefaults() *AuditFeedEvent {
	this := AuditFeedEvent{}
	return &this
}

// GetId returns the Id field value
func (o *AuditFeedEvent) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AuditFeedEvent) SetId(v int64) {
	o.Id = v
}

// GetTime returns the Time field value
func (o *AuditFeedEvent) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *AuditFeedEvent) SetTime(v time.Time) {
	o.Time = v
}

// GetOrgId returns the OrgId field value
func (o *AuditFeedEvent) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *AuditFeedEvent) SetOrgId(v string) {
	o.OrgId = v
}

// GetAgentId returns the AgentId field value
func (o *AuditFeedEvent) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *AuditFeedEvent) SetAgentId(v string) {
	o.AgentId = v
}

// GetItemId returns the ItemId field value
func (o *AuditFeedEvent) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *AuditFeedEvent) SetItemId(v string) {
	o.ItemId = v
}

// GetAction returns the Action field value
func (o *AuditFeedEvent) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *AuditFeedEvent) SetAction(v string) {
	o.Action = v
}

// GetDecision returns the Decision field value
func (o *AuditFeedEvent) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *AuditFeedEvent) SetDecision(v string) {
	o.Decision = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AuditFeedEvent) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AuditFeedEvent) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AuditFeedEvent) SetReason(v string) {
	o.Reason = &v
}

// GetApprovalId returns the ApprovalId field value if set, zero value otherwise.
func (o *AuditFeedEvent) GetApprovalId() string {
	if o == nil || IsNil(o.ApprovalId) {
		var ret string
		return ret
	}
	return *o.ApprovalId
}

// GetApprovalIdOk returns a tuple with the ApprovalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditFeedEvent) GetApprovalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalId) {
		return nil, false
	}
	return o.ApprovalId, true
}

// HasApprovalId returns a boolean if a field has been set.
func (o *AuditFeedEvent) HasApprovalId() bool {
	if o != nil && !IsNil(o.ApprovalId) {
		return true
	}

	return false
}

// SetApprovalId gets a reference to the given string and assigns it to the ApprovalId field.
func (o *AuditFeedEvent) SetApprovalId(v string) {
	o.ApprovalId = &v
}

func (o AuditFeedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditFeedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["time"] = o.Time
	toSerialize["org_id"] = o.OrgId
	toSerialize["agent_id"] = o.AgentId
	toSerialize["item_id"] = o.ItemId
	toSerialize["action"] = o.Action
	toSerialize["decision"] = o.Decision
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.ApprovalId) {
		toSerialize["approval_id"] = o.ApprovalId
	}
	return toSerialize, nil
}

func (o *AuditFeedEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"time",
		"org_id",
		"agent_id",
		"item_id",
		"action",
		"decision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditFeedEvent := _AuditFeedEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuditFeedEvent)

	if err != nil {
		return err
	}

	*o = AuditFeedEvent(varAuditFeedEvent)

	return err
}

type NullableAuditFeedEvent struct {
	value *AuditFeedEvent
	isSet bool
}

func (v NullableAuditFeedEvent) Get() *AuditFeedEvent {
	return v.value
}

func (v *NullableAuditFeedEvent) Set(val *AuditFeedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditFeedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditFeedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditFeedEvent(val *AuditFeedEvent) *NullableAuditFeedEvent {
	return &NullableAuditFeedEvent{value: val, isSet: true}
}

func (v NullableAuditFeedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditFeedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


