/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestsResponse{}

// RequestsResponse struct for RequestsResponse
type RequestsResponse struct {
	Requests []ApprovalRequest `json:"requests"`
}

type _RequestsResponse RequestsResponse

// NewRequestsResponse instantiates a new RequestsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsResponse(requests []ApprovalRequest) *RequestsResponse {
	this := RequestsResponse{}
	this.Requests = requests
	return &this
}

// NewRequestsResponseWithDefaults instantiates a new RequestsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsResponseWithDefaults() *RequestsResponse {
	this := RequestsResponse{}
	return &this
}

// GetRequests returns the Requests field value
func (o *RequestsResponse) GetRequests() []ApprovalRequest {
	if o == nil {
		var ret []ApprovalRequest
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *RequestsResponse) GetRequestsOk() ([]ApprovalRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requests, true
}

// SetRequests sets field value
func (o *RequestsResponse) SetRequests(v []ApprovalRequest) {
	o.Requests = v
}

func (o RequestsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests
	return toSerialize, nil
}

func (o *RequestsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestsResponse := _RequestsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestsResponse)

	if err != nil {
		return err
	}

	*o = RequestsResponse(varRequestsResponse)

	return err
}

type NullableRequestsResponse struct {
	value *RequestsResponse
	isSet bool
}

func (v NullableRequestsResponse) Get() *RequestsResponse {
	return v.value
}

func (v *NullableRequestsResponse) Set(val *RequestsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsResponse(val *RequestsResponse) *NullableRequestsResponse {
	return &NullableRequestsResponse{value: val, isSet: true}
}

func (v NullableRequestsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


