/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
)

// checks if the ApproveRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveRequestBody{}

// ApproveRequestBody struct for ApproveRequestBody
type ApproveRequestBody struct {
	// Go duration for the grant approval lifetime (default 15m).
	Ttl *string `json:"ttl,omitempty"`
}

// NewApproveRequestBody instantiates a new ApproveRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveRequestBody() *ApproveRequestBody {
	this := ApproveRequestBody{}
	return &this
}

// NewApproveRequestBodyWithDefaults instantiates a new ApproveRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveRequestBodyWithDefaults() *ApproveRequestBody {
	this := ApproveRequestBody{}
	return &this
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *ApproveRequestBody) GetTtl() string {
	if o == nil || IsNil(o.Ttl) {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproveRequestBody) GetTtlOk() (*string, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *ApproveRequestBody) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the Ttl field.
func (o *ApproveRequestBody) SetTtl(v string) {
	o.Ttl = &v
}

func (o ApproveRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

type NullableApproveRequestBody struct {
	value *ApproveRequestBody
	isSet bool
}

func (v NullableApproveRequestBody) Get() *ApproveRequestBody {
	return v.value
}

func (v *NullableApproveRequestBody) Set(val *ApproveRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveRequestBody(val *ApproveRequestBody) *NullableApproveRequestBody {
	return &NullableApproveRequestBody{value: val, isSet: true}
}

func (v NullableApproveRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


