/*
Veil

Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package veil

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApprovalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalRequest{}

// ApprovalRequest struct for ApprovalRequest
type ApprovalRequest struct {
	Id string `json:"id"`
	AgentId string `json:"agent_id"`
	ItemId string `json:"item_id"`
	GrantId string `json:"grant_id"`
	Action string `json:"action"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// The Kratos identity of the owner who answered — first write wins.
	ResolvedBy *string `json:"resolved_by,omitempty"`
	// The grant approval created by an approve resolution.
	ApprovalId *string `json:"approval_id,omitempty"`
}

type _ApprovalRequest ApprovalRequest

// NewApprovalRequest instantiates a new ApprovalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalRequest(id string, agentId string, itemId string, grantId string, action string, status string, createdAt time.Time, expiresAt time.Time) *ApprovalRequest {
	this := ApprovalRequest{}
	this.Id = id
	this.AgentId = agentId
	this.ItemId = itemId
	this.GrantId = grantId
	this.Action = action
	this.Status = status
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewApprovalRequestWithDefaults instantiates a new ApprovalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalRequestWithDefaults() *ApprovalRequest {
	this := ApprovalRequest{}
	return &this
}

// GetId returns the Id field value
func (o *ApprovalRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApprovalRequest) SetId(v string) {
	o.Id = v
}

// GetAgentId returns the AgentId field value
func (o *ApprovalRequest) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *ApprovalRequest) SetAgentId(v string) {
	o.AgentId = v
}

// GetItemId returns the ItemId field value
func (o *ApprovalRequest) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *ApprovalRequest) SetItemId(v string) {
	o.ItemId = v
}

// GetGrantId returns the GrantId field value
func (o *ApprovalRequest) GetGrantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantId
}

// GetGrantIdOk returns a tuple with the GrantId field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetGrantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantId, true
}

// SetGrantId sets field value
func (o *ApprovalRequest) SetGrantId(v string) {
	o.GrantId = v
}

// GetAction returns the Action field value
func (o *ApprovalRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ApprovalRequest) SetAction(v string) {
	o.Action = v
}

// GetStatus returns the Status field value
func (o *ApprovalRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApprovalRequest) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApprovalRequest) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApprovalRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *ApprovalRequest) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *ApprovalRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetResolvedAt returns the ResolvedAt field value if set, zero value otherwise.
func (o *ApprovalRequest) GetResolvedAt() time.Time {
	if o == nil || IsNil(o.ResolvedAt) {
		var ret time.Time
		return ret
	}
	return *o.ResolvedAt
}

// GetResolvedAtOk returns a tuple with the ResolvedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetResolvedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResolvedAt) {
		return nil, false
	}
	return o.ResolvedAt, true
}

// HasResolvedAt returns a boolean if a field has been set.
func (o *ApprovalRequest) HasResolvedAt() bool {
	if o != nil && !IsNil(o.ResolvedAt) {
		return true
	}

	return false
}

// SetResolvedAt gets a reference to the given time.Time and assigns it to the ResolvedAt field.
func (o *ApprovalRequest) SetResolvedAt(v time.Time) {
	o.ResolvedAt = &v
}

// GetResolvedBy returns the ResolvedBy field value if set, zero value otherwise.
func (o *ApprovalRequest) GetResolvedBy() string {
	if o == nil || IsNil(o.ResolvedBy) {
		var ret string
		return ret
	}
	return *o.ResolvedBy
}

// GetResolvedByOk returns a tuple with the ResolvedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetResolvedByOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedBy) {
		return nil, false
	}
	return o.ResolvedBy, true
}

// HasResolvedBy returns a boolean if a field has been set.
func (o *ApprovalRequest) HasResolvedBy() bool {
	if o != nil && !IsNil(o.ResolvedBy) {
		return true
	}

	return false
}

// SetResolvedBy gets a reference to the given string and assigns it to the ResolvedBy field.
func (o *ApprovalRequest) SetResolvedBy(v string) {
	o.ResolvedBy = &v
}

// GetApprovalId returns the ApprovalId field value if set, zero value otherwise.
func (o *ApprovalRequest) GetApprovalId() string {
	if o == nil || IsNil(o.ApprovalId) {
		var ret string
		return ret
	}
	return *o.ApprovalId
}

// GetApprovalIdOk returns a tuple with the ApprovalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalRequest) GetApprovalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalId) {
		return nil, false
	}
	return o.ApprovalId, true
}

// HasApprovalId returns a boolean if a field has been set.
func (o *ApprovalRequest) HasApprovalId() bool {
	if o != nil && !IsNil(o.ApprovalId) {
		return true
	}

	return false
}

// SetApprovalId gets a reference to the given string and assigns it to the ApprovalId field.
func (o *ApprovalRequest) SetApprovalId(v string) {
	o.ApprovalId = &v
}

func (o ApprovalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["agent_id"] = o.AgentId
	toSerialize["item_id"] = o.ItemId
	toSerialize["grant_id"] = o.GrantId
	toSerialize["action"] = o.Action
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.ResolvedAt) {
		toSerialize["resolved_at"] = o.ResolvedAt
	}
	if !IsNil(o.ResolvedBy) {
		toSerialize["resolved_by"] = o.ResolvedBy
	}
	if !IsNil(o.ApprovalId) {
		toSerialize["approval_id"] = o.ApprovalId
	}
	return toSerialize, nil
}

func (o *ApprovalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"agent_id",
		"item_id",
		"grant_id",
		"action",
		"status",
		"created_at",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApprovalRequest := _ApprovalRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApprovalRequest)

	if err != nil {
		return err
	}

	*o = ApprovalRequest(varApprovalRequest)

	return err
}

type NullableApprovalRequest struct {
	value *ApprovalRequest
	isSet bool
}

func (v NullableApprovalRequest) Get() *ApprovalRequest {
	return v.value
}

func (v *NullableApprovalRequest) Set(val *ApprovalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalRequest(val *ApprovalRequest) *NullableApprovalRequest {
	return &NullableApprovalRequest{value: val, isSet: true}
}

func (v NullableApprovalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


